### ISSUE TITLE
Keep history of ratings

### ISSUE THREAD

**Issue by enjalot** [ktalattinis/ratingslib#1]
It would be nice to be able to keep the ratings history after each match so that ratings can be visualized changing over time.
I was able to hack this by saving `new_ratings` in an array by modifying a copy of the Elo class to make visualizations like this:

<img width="624" alt="Screenshot 2023-06-22 at 1 04 29 PM" src="https://github.com/ktalattinis/ratingslib/assets/96189/809b9694-c758-4776-bc57-a58d4d47f257">

I'm not sure how to structure it so that it could be done regardless of rating system

**Comment by ktalattinis** [comment]
You can plot the history of ratings by using the function `plot_ratings` in [ratingslib/ratings/methods.py](https://github.com/ktalattinis/ratingslib/blob/main/ratingslib/ratings/methods.py). Also, an example in [examples/sports/soccer_plot_ratings.py](https://github.com/ktalattinis/ratingslib/blob/main/examples/sports/soccer_plot_ratings.py) is provided to demonstrate how the function works.
